#!/usr/bin/env ruby

commit_msg_file_path = ARGV[0]
current_branch = `git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,'`.split('/').last.strip

starts_with_digits_re = /^(\d+).*/
if starts_with_digits_re.match(current_branch)
  issue_nr = starts_with_digits_re.match(current_branch)[1]
end
puts "Issue nr: #{issue_nr}"

file = File.open(commit_msg_file_path)

commit_msg = file.readline
puts "Old commit msg: #{commit_msg}"

issue_nr_in_brackets = /^\[#{issue_nr}\]/
starts_with_issue_nr = /^#{issue_nr}_/

if starts_with_issue_nr.match(commit_msg)
  commit_msg.sub!(issue_nr, "[#{issue_nr}]")
end

if !issue_nr_in_brackets.match(commit_msg)
  commit_msg = "[#{issue_nr}] #{commit_msg}"
end

puts "New commit msg: #{commit_msg}"

exit 1
#Start of commit msg
#If matches branch issue_no, add brackets
#If issue_no in brackets, leave alone
#If something else add issue no in brackets

