#!/usr/bin/env ruby

commit_msg_path = ARGV[0]
current_branch = `git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,'`.split('/').last.strip

starts_with_digits_re = /^(\d+).*/
if starts_with_digits_re.match(current_branch)
  issue_nr = starts_with_digits_re.match(current_branch)[1]
end

new_message = File.open(commit_msg_path, 'r+') do |file|
  first_line = file.readline
  
  starts_with_issue_nr = /^#{issue_nr}.*/
  if starts_with_issue_nr.match(first_line)
    first_line.sub!(issue_nr, "[#{issue_nr}]")
  end

  issue_nr_in_brackets = /^\[#{issue_nr}\]/
  if !issue_nr_in_brackets.match(first_line)
    first_line = "[#{issue_nr}] #{first_line}"
  end

  new_message = first_line

  file.each_line do |line|
    new_message << line
  end
  new_message
end

File.open(commit_msg_path, 'w') {|file| file.write(new_message)}


#Start of commit msg
#If matches branch issue_no, add brackets
#If issue_no in brackets, leave alone
#If something else add issue no in brackets

