#!/usr/bin/env ruby

protected_branches=['master', 'prod']
yeses = ['y', 'Y', 'yes']
current_branch = `git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,'`.split('/').last.strip
STDIN.reopen('/dev/tty')

if protected_branches.include?(current_branch)
  puts "You're about to commit to master, is that what you intended? [y|n] "
  response = $stdin.gets.strip

  if yeses.include?(response)
    exit 0 # push will execute
  else
    exit 1 # push will not execute
  end
else
  exit 0 #push will execute
end



